"""
Web version of the Smart Study Notes Generator (used for Hugging Face Spaces).

It reuses the summarization logic from app.py and adds a simple Gradio
page on top, so the same BART model and calculations are used in both
the command-line and web versions.

Run locally with:  python web_app.py
"""

import gradio as gr

from app import (
    load_model,
    validate_input,
    generate_summary,
    count_words,
    reduction_percentage,
    extract_key_points,
)

# Load the model once when the web app starts.
summarizer = load_model()


def make_notes(text):
    """Called by Gradio when the user clicks the button."""
    if summarizer is None:
        raise gr.Error("The summarization model could not be loaded.")

    error = validate_input(text)
    if error:
        raise gr.Error(error)

    try:
        summary = generate_summary(summarizer, text)
    except Exception as err:
        raise gr.Error(f"Something went wrong while summarizing ({err}).")

    original_count = count_words(text)
    summary_count = count_words(summary)
    reduction = reduction_percentage(original_count, summary_count)
    key_points = "\n".join(f"• {p}" for p in extract_key_points(summary))

    return summary, original_count, summary_count, f"{reduction:.2f}%", key_points


# Load the three sample paragraphs (the long lines in sample_inputs.txt).
with open("sample_inputs.txt", encoding="utf-8") as f:
    examples = [[line.strip()] for line in f if len(line) > 300]

with gr.Blocks(title="Smart Study Notes Generator") as demo:
    gr.Markdown("# Smart Study Notes Generator")
    gr.Markdown("Paste a paragraph to get a short summary and key points, "
                "generated by the pre-trained BART model (facebook/bart-large-cnn).")

    text_input = gr.Textbox(label="Paragraph", lines=8,
                            placeholder="Paste at least 30 words of text here...")
    button = gr.Button("Generate Notes", variant="primary")

    summary_out = gr.Textbox(label="Generated Summary", lines=4)
    with gr.Row():
        original_out = gr.Number(label="Original Word Count")
        summary_count_out = gr.Number(label="Summary Word Count")
        reduction_out = gr.Textbox(label="Text Reduction")
    key_points_out = gr.Textbox(label="Key Points", lines=5)

    gr.Examples(examples=examples, inputs=text_input)

    button.click(
        make_notes,
        inputs=text_input,
        outputs=[summary_out, original_out, summary_count_out, reduction_out, key_points_out],
    )

if __name__ == "__main__":
    demo.launch()
